services:
  nginx:
    image: nginx:latest
    container_name: aigument-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/chat-html:/usr/share/nginx/html:ro # 테스트용 html
      - ./nginx/auth-html:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - aigument-network

  app:
    build: .
    container_name: aigument-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/aigument_db?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      OLLAMA_BASE_URL: http://ai-engine:11434
      AI_ENGINE_URL: http://ai-engine:8000
      JWT_SECRET: ${JWT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      MAIN_PAGE_URL: ${MAIN_PAGE_URL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      ai-engine:
        condition: service_started
    networks:
      - aigument-network

  ai-engine:
    image: ollama/ollama:latest
    container_name: aigument-ai
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - aigument-network

  db:
    image: mysql:8.0
    container_name: aigument-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: aigument_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - aigument-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: aigument-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    networks:
      - aigument-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  aigument-network:
    driver: bridge